version: '3.8'

services:
  # api-gateway:
  #   image: caddy:2.2.1-alpine
  #   volumes:
  #       - ./caddy:/etc/caddy
  #       - ./html:/srv
  #   ports:
  #       - "80:80"
  #       - "443:443"

  store-service-stub:
    image: andyrbell/mountebank:2.3.2
    volumes:
      - ./mountebank/:/imposters/
    ports:
      - "8000:8000"
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/store-service.json',
        '--allowInjection'
      ]
