services:
  # api-gateway:
  #   image: caddy:2.2.1-alpine
  #   volumes:
  #       - ./caddy:/etc/caddy
  #       - ./html:/srv
  #   ports:
  #       - "80:80"
  #       - "443:443"

  store-service-stub:
    image: bbyars/mountebank:2.9.1
    volumes:
      - ./mountebank/:/imposters/
    ports:
      - "8000:8000"
    working_dir: /imposters
    command:
      [
        'start',
        '--configfile',
        'store-service.json',
        '--allowInjection'
      ]
